# Generated by Django 6.0.5 on 2026-05-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="telefono",
            field=models.CharField(max_length=10),
        ),
    ]
